import { Offer } from "./offers.types";

export const PUBLIC_MOCK_OFFERS: Offer[] = [
  {
    id: "public_offer_1",
    title: "₹200 OFF",
    description: "First booking discount",
    code: "FIRST200",
    category: "all",
    minimumBookingAmount: 799,
    validUntil: "2026-12-31T23:59:59Z",
    status: "available",
    saved: false,
  },
  {
    id: "public_offer_2",
    title: "20% OFF",
    description: "Home cleaning services",
    code: "CLEAN20",
    category: "cleaning",
    maximumDiscount: 300,
    validUntil: "2026-10-31T23:59:59Z",
    status: "available",
    saved: false,
  },
  {
    id: "public_offer_3",
    title: "₹150 OFF",
    description: "AC service",
    code: "COOL150",
    category: "appliances",
    minimumBookingAmount: 999,
    validUntil: "2026-09-30T23:59:59Z",
    status: "available",
    saved: true,
  },
  {
    id: "public_offer_4",
    title: "15% OFF",
    description: "Salon at home",
    code: "BEAUTY15",
    category: "beauty",
    validUntil: "2026-11-15T23:59:59Z",
    status: "available",
    saved: false,
  },
  {
    id: "public_offer_5",
    title: "₹100 OFF",
    description: "Plumbing services",
    code: "FIX100",
    category: "repairs",
    validUntil: "2026-09-20T23:59:59Z",
    status: "limited",
    saved: false,
  },
  {
    id: "public_offer_6",
    title: "10% OFF",
    description: "Home maintenance",
    code: "HOME10",
    category: "maintenance",
    validUntil: "2026-10-15T23:59:59Z",
    status: "available",
    saved: false,
  }
];
