"use client";

import { motion } from "framer-motion";
import { Sparkles, TrendingUp, AlertCircle } from "lucide-react";
import { FeedbackTheme } from "@/types/vendor";
import { cn } from "@/lib/utils";

interface FeedbackThemesProps {
  themes: FeedbackTheme[];
}

export function FeedbackThemes({ themes }: FeedbackThemesProps) {
  const positive = themes.filter(t => t.type === "positive");
  const improvement = themes.filter(t => t.type === "improvement");
  const maxMentions = Math.max(...themes.map(t => t.mentions));

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.2 }}
      className="bg-white rounded-3xl border border-slate-100 shadow-sm p-6 md:p-8"
    >
      <div className="flex items-center justify-between mb-1">
        <h3 className="font-bold text-slate-900">Feedback Themes</h3>
        <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest bg-slate-50 border border-slate-200 px-2 py-1 rounded-full">
          Demo Analysis
        </span>
      </div>
      <p className="text-xs text-slate-400 mb-6">Demo feedback analysis — not generated by AI.</p>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        {/* Positive */}
        <div>
          <div className="flex items-center gap-2 mb-3">
            <TrendingUp className="w-4 h-4 text-emerald-500" />
            <span className="text-sm font-bold text-emerald-700">What customers praise</span>
          </div>
          <div className="space-y-3">
            {positive.map((theme, i) => (
              <motion.div
                key={theme.label}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.3 + i * 0.06 }}
              >
                <div className="flex items-center justify-between mb-1">
                  <span className="text-sm font-medium text-slate-700">{theme.label}</span>
                  <span className="text-xs font-bold text-slate-500">{theme.mentions}</span>
                </div>
                <div className="h-2 bg-emerald-50 rounded-full overflow-hidden">
                  <motion.div
                    className="h-full bg-emerald-400 rounded-full"
                    initial={{ width: 0 }}
                    animate={{ width: `${(theme.mentions / maxMentions) * 100}%` }}
                    transition={{ duration: 0.8, ease: "easeOut", delay: 0.4 + i * 0.06 }}
                  />
                </div>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Improvement */}
        <div>
          <div className="flex items-center gap-2 mb-3">
            <AlertCircle className="w-4 h-4 text-amber-500" />
            <span className="text-sm font-bold text-amber-700">Areas mentioned</span>
          </div>
          <div className="space-y-3">
            {improvement.map((theme, i) => (
              <motion.div
                key={theme.label}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.3 + i * 0.06 }}
              >
                <div className="flex items-center justify-between mb-1">
                  <span className="text-sm font-medium text-slate-700">{theme.label}</span>
                  <span className="text-xs font-bold text-slate-500">{theme.mentions}</span>
                </div>
                <div className="h-2 bg-amber-50 rounded-full overflow-hidden">
                  <motion.div
                    className="h-full bg-amber-400 rounded-full"
                    initial={{ width: 0 }}
                    animate={{ width: `${(theme.mentions / maxMentions) * 100}%` }}
                    transition={{ duration: 0.8, ease: "easeOut", delay: 0.4 + i * 0.06 }}
                  />
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </motion.div>
  );
}
